GET localhost:8080/api/v3/github/users/Przemyslaw-Swiderski/repos
Accept: application/json

###

GET localhost:8080/api/v3/github/users/xxx-notfounduser/repos
Accept: application/json

###

GET localhost:8080/api/v3/github/users/Przemyslaw-Swiderski/repos
Accept: application/xml

###

GET https://api.github.com/users/Przemyslaw-Swiderski/repos
Accept: application/json

